import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@fontsource/poppins";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/400-italic.css";
import { Roboto } from "next/font/google";
import { Box } from "@mui/material";
// import SideCheckSecond from "../Components/Layout/SideCheckSecondLayout";
import SideCheck from "../../Components/Layout/SideCheck";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../api/auth/[...nextauth]/route";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Bench Education",
  description: "Generated by Walton Digitech",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  const UserType = session && session?.user?.data?.user_type;

  console.log("session", UserType);
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <link rel="icon" href="/images/sidenav/logo1-2.png" />
      </head>
      <body>
        <Box>
          <SideCheck UserType={UserType} session={session}>
            {children} <ToastContainer />
          </SideCheck>
        </Box>
      </body>
    </html>
  );
}
